salt/map.jinja

this will fix #84 sorry about not thinking of backward compatibility.

fix #84 with same logic as dnsmasq-formula

---

salt/files/cloud.providers.d/saltify.conf

This is necessary for the correct settings on the minions when saltifying new hosts

saltify provider should set correct master

---

pillar.example
salt/map.jinja

Archlinux has salt-raet or salt-zmq in repository, I have choosen salt-zmq as default in map.jinja
Improved the override function without the base='default' parameter, so to be backward compatible to 0.17 salt version see pillar.example for lookup function override.

Updated map.jinja for archlinux package convention

---

pillar.example
salt/files/master.d/_defaults.conf

Added rest tornado configuration options to salt-master _defaults.conf
see pillar.example for configuration

added rest_tornado to _defaults.conf

---

pillar.example
salt/files/minion.d/_defaults.conf

This will fix #39 
And it will be backwards compatible with the current pillar configuration.

Fix #39 multi master support to minion

---

salt/pkgrepo/init.sls

fixes #83 by wrapping contents of pkgrepo/init.sls in an {% if %}.
Change-Id: I8260fdf5cf802c0b28197516da374add6c3002a2

don't try to load pkgrepo on non-Debian distros

---

salt/files/minion.d/_defaults.conf

Make the mine_interval time configurable with the salt-formula.
only option from the mine_functions that cannot be set with pillar data
see:
http://docs.saltstack.com/en/latest/topics/mine/#mine-interval

create config option for mine_interval

---

pillar.example
salt/defaults.yaml
salt/master.sls
salt/minion.sls
salt/standalone.sls

New versions of Salt put config files in /etc/salt/{minion,master}.d. We don't
want to erase them by using a clean: True on the file.recurse. This is a
backward incompatible change, but it's necessary to avoid deleting Salt config
files.

Stop using clean: True on /etc/salt/{minion,master}.d

---

pillar.example
salt/api.sls
salt/cloud.sls
salt/defaults.yaml
salt/master.sls
salt/minion.sls
salt/ssh.sls
salt/standalone.sls
salt/syndic.sls

If you are installing Salt via git/pip, the formula will try to overwrite your
install with packaged versions. This setting makes it possible to avoid that.

Add setting to not install packages

---

salt/api.sls

fix recursion in formula depency should be on master service.

Fix recursion in api.service

---

pillar.example
salt/files/minion.d/f_defaults.conf

I'm not sure why mine_interval is included in the conf file but mine_functions isn't. Up till now I've been adding a separate file to manage it in my own installation, but this seems like something the formula should support.

Added mine_functions to f_defaults.conf.

---

salt/ssh.sls

The 'require' statement needs a list as input, but doesn't get
any input when install_packages is set to False.

Exclude require statement when install_packages is False.

---

pillar.example
salt/cloud.sls
salt/defaults.yaml
salt/files/cloud.providers.d/ec2.conf
salt/files/cloud.providers.d/gce.conf
salt/files/cloud.providers.d/rsos.conf
salt/files/cloud.providers.d/saltify.conf

The default profile and map templates are neither terribly useful nor easy to add to without having to maintain your own fork or extension state. This patch makes the state use file.recurse for those folders (instead of assuming one file per provider) and allows the source property to be set. I don't *think* it can break existing salt trees.
I didn't include providers.d because the templates in there don't gracefully handle missing pillar data.
...but I'm not certain this is actually the best way to do this. I'm looking at the salt.cloud sls, and thinking that with a bit of refactoring the providers, profiles, maps, and file.directory section could all be collapsed into a single loop like the one in this commit -- and be both more flexible and require less pillar configuration afterward. …

Added pillar option to redirect profile and map folders.

---

salt/files/cloud.profiles.d/ec2.conf
salt/files/cloud.profiles.d/gce.conf
salt/files/cloud.providers.d/ec2.conf
salt/files/cloud.providers.d/gce.conf

I missed something on the last PR. salt-cloud will attempt to load or connect to all the available profiles/providers even if they're not explicitly asked for. Having templates in place with default values produces a bunch of error spam, even though it doesn't stop things from working. I missed that while testing, sorry.
This patch makes the ec2/gce templates blank themselves if the default templates are used and appropriate pillar data isn't present. rsos already has the necessary behavior. Saltify doesn't seem to need it.
There may be a better way to do this; this was just the first method I came up with that required minimal configuration.
Side note: I sort of wonder if it wouldn't be a good idea to have just one default template, that takes the entire provider/profile/map …

ec2/gce profiles/providers are no longer configured if they are not used

---

salt/files/minion.d/f_defaults.conf

The user will already have it's /etc/salt/minion file, so it doesn't need all this info, and it makes easier to know what has been generated and what not

Cleanup template for easier user reading

---

pillar.example

pillar_roots definitions are missing from pillar.example
I believe this is an afterthought, thus I have added them to pillar.example

add pillar_roots for minion and master in pillar.example

---

salt/files/master.d/f_defaults.conf

This commit fixes how `pillar_roots` are generated and after this fix the
generated configuration does not contain any unnecessary new lines:
```yaml
pillar_roots:
base:
/srv/salt/dir1
dev:
/srv/salt/dir2
/srv/salt/dir3
locale:
/srv/salt/dir4
```
Before this commit the pillar_roots in `f_defaults.conf` for master would be
generated with a lot of empty lines in between directories, like this:
```yaml
pillar_roots:
base:
/srv/salt/dir1
dev:
/srv/salt/dir2
/srv/salt/dir3
local:
/srv/salt/dir4
```
The minion configuration is not affected and renders fine.

Fix pillar_roots configuration format in master

---

README.rst
salt/gitfs/pygit2.sls
salt/map.jinja
salt/pkgrepo/init.sls
salt/pkgrepo/redhat/init.sls

* Install pygit from package
* Add Official Salt ZeroMQ 4 COPR repository
Note that Salt itself is assumed to already to be available to the system via yum, via EPEL for example

Improved support for Enterprise Linux family OSs (CentOS, RHEL etc)

---

salt/gitfs/pygit2.sls

Pygit2 requires git itself. This installs it in all cases.

The git command line tool is a requirement of pygit2

---

salt/cloud.sls
salt/master.sls
salt/minion.sls
salt/pkgrepo/debian/init.sls
salt/ssh.sls
salt/standalone.sls

Please test this, it works on 2015.5.x but {{ slspath }} isn't available on 2014.1 and below,
see also this issue : https://github.com/saltstack/salt/issues/4348

Remove hardcoded paths with {{ slspath }} variable

---

salt/formulas.jinja

As described in https://docs.python.org/2/library/string.html
> Changed in version 2.7: The positional argument specifiers can be omitted, so '{} {}' is equivalent to '{0} {1}'.
In python 2.6 this feature is not available.
CentOS 6.5 still has python 2.6, so it would be nice to support it.

formulas.jinja: python 2.6 support

---

salt/syndic.sls

The syndic service was depending upon itself, which caused the salt run
to fail. This commit fixes that by depending on the salt-master service
rather than the salt-syndic service. I also made it more general by
using IDs to specify the provider rather than the name, which is a bit
less reliable.

Fix syndic requisites

---

salt/api.sls

Seems there are several colons missing for salt.api to work correctly, hope I found all of them

salt.api state fails

---

salt/defaults.yaml
salt/gitfs/gitpython.sls
salt/map.jinja

This change tweaks the GitPython package installation state to support
alternate package names (on FreeBSD, it's called "py27-GitPython").
Also, on FreeBSD salt-ssh is included in the "py27-salt" package by
default, requiring an update to `distro_map`.

Add support for GitPython and salt-ssh on FreeBSD masters

---

salt/map.jinja

On FreeBSD salt-ssh gets bundled into a single package with the other
SaltStack components (minion, master, etc.).

Use the py27-salt package when installing salt-ssh on FreeBSD

---

salt/defaults.yaml
salt/gitfs/gitpython.sls
salt/map.jinja

Note that this requires alterations to both *salt/defaults.yaml* and *salt/map.jinja* to allow customization of the GitPython package name.

Use the py27-GitPython package when installing GitPython on FreeBSD

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

The two options ``master_sign_pubkey`` and ``verify_master_pubkey_sign`` are needed for proper mutli-master setup with failover. The setup is described [here](http://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html).
Somehow they are not present in [master configuration](https://github.com/saltstack/salt/blob/develop/conf/master), but actually work.

Add options for mult-master setup

---

salt/files/master.d/f_defaults.conf

With a simple pillar like this::
$ sudo salt-call --config-dir /srv/etc/bootstrap --pillar-root /srv/pillar pillar.get salt:pillar_roots
local:
----------
base:
- /srv/pillar
This was generated in /etc/salt/master.d/f_defaults.conf::
pillar_roots:base:- /srv/pillar
#
Resulting in parse errors by salt::
$ sudo salt '*' state.highstate
[ERROR   ] Error parsing configuration file: /etc/salt/master.d/f_defaults.conf - while scanning a simple key
in "<string>", line 531, column 1:
pillar_roots:base:- /srv/pillar
^
could not found expected ':'
in "<string>", line 532, column 1:
#
^
[ERROR   ] Error parsing configuration file: /etc/salt/master.d/f_defaults.conf - while scanning a simple key
in "<string>", line 531, column 1:
pillar_roots:base:- /srv/pillar
^
could not found expected ':'
in …

Fixed pillar_roots generation for salt-master.

---

salt/api.sls

Without this change, the `salt.api` formula starts the service, but this configuration does not persist if the computer reboots.

Configure the salt-api service to start at boot time

---

salt/defaults.yaml
salt/gitfs/pygit2.sls
salt/map.jinja

Added ability to specify version for pygit2 and libgit2 (when libgit2 is not provided by a package) via pillar. More importantly, leveraged this feature to make Debian-based distros install libgit2 via package instead of source.

Improve flexibility/quality of pygit2 state

---

salt/formulas.jinja

This test isn't available in certain popular versions of Jinja (namely the one
installed by default in CentOS 6).

Remove mapping test

---

salt/defaults.yaml
salt/gitfs/pygit2.sls
salt/map.jinja

pygit2 state installs git package using 'git' state ID, which is also used by the git-formula state. Changes in this PR permit delegation to another state for git dependency, or alternatively installs git with state ID of 'pygit2-git', to prevent ID conflicts.

Fixed conflict with git-formula

---

salt/formulas.jinja
salt/formulas.sls

Jinja macros are not actually functions.  The only thing they can return
is a string.  In order to return structured data, the callee must
serialize it, and the caller must deserialize it.  This state formula
uses YAML as the intermediary, hence the occurrence of both the
`|yaml` (callee) and `|load_yaml` (caller) filters in its code.
The post-render "mapping values are not allowed here" error in
*salt/formulas.sls* or the broken rendering of
*salt/files/master.d/f_defaults.conf* happens because invocations of the
`formulas_git_opt` macro in several Jinja `set` statements do not get
deserialized, resulting in the trailing newline followed by three dot
characters (`...`), which YAML uses to signal the end of a document.
Correcting these rendering errors requires adding the necessary …

Filter all calls to formulas_git_opt through load_yaml

---

salt/files/minion.d/f_defaults.conf

The multi-master setup (support of which I added in #161) won't actually work without this paramter.
Sorry for forgeting that in first PR.

Add master_type option

---

salt/files/master.d/f_defaults.conf

This allows user to follow up on jobs a lot easier.

Manage show_jid option in master configuration

---

salt/syndic.sls

Previously:
```
----------
ID: salt-syndic
Function: service.running
Result: False
Comment: The named service salt-syndic is not available
Started: 15:36:38.106414
Duration: 28.398 ms
Changes:   
Summary
------------
Succeeded: 5
Failed:    1
------------
```
With this additional line:
```
----------
ID: salt-syndic
Function: service.running
Name: salt_syndic
Result: True
Comment: The service salt_syndic is already running
Started: 15:40:58.786103
Duration: 113.044 ms
Changes:   
Summary
------------
Succeeded: 6
Failed:    0
------------
Total states run:     6
```
Tested on FreeBSD 10.2 and CentOS 6.7 with Salt 2015.5.x

use salt_settings.syndic_service so state works on FreeBSD, too

---

salt/files/minion.d/f_defaults.conf

if a special structure is required for master, it'll use whatever's defined in pillar.
Seems to resolve #178

Never fall back to `cfg_salt['master']` in minion config

---

salt/files/master.d/f_defaults.conf

Now it is possible to accept multiple declaration both in ext_pillar and master_tops as documented here:
- https://docs.saltstack.com/en/latest/topics/development/external_pillars.html#configuration
- https://docs.saltstack.com/en/latest/topics/master_tops/index.html

fixed ext_pillar and master_tops to get more options

---

salt/map.jinja
salt/pkgrepo/debian/absent.sls
salt/pkgrepo/debian/init.sls
salt/pkgrepo/debian/sources.list

…and allow the repo name and key_url to be overridden via Pillar lookup. I've created this so I can switch over to repo.saltstack.com but hopefully kept the formula backward-compatible.

Make Debian use pkgrepo.managed

---

salt/pkgrepo/debian/init.sls

The clean_file parameter is ignored on versions before 2015.8 but is useful.

Add clean_file to wipe saltstack.list contents

---

salt/pkgrepo/ubuntu/absent.sls
salt/pkgrepo/ubuntu/init.sls

It seems that Ubuntu's PPA's are currently out of date and no longer maintained (newest release is 2015.5.3).  This change allows adding the official SaltStack PPA's

Dropped ppa and updated to official repos for ubuntu

---

pillar.example
salt/formulas.jinja
salt/formulas.sls

Currently the `baseurl` specified for downloading formulas using the `formula.sls` state is aligned with a specific environment. This means, that you cannot download formulas from different URLs into the *same* environment, however you can create a new environment using a different `baseurl`.
This creates a significant restriction on the ability to construct an environment that will source formulas from a variety of sources.
This pull request adds the ability to specify multiple URLs for a single environment.
Couple of notes:
* It adds some complexity to the pillar, where a `baseurl` *must* be specified for each environment
* It (probably more importantly) breaks backwards compatibility with earlier versions. This could probably be resolved by using the *default* `baseurl` specified in …

Support for downloading formulas from multiple baseurls into same environment

---

pillar.example
salt/formulas.jinja
salt/formulas.sls

This restores the original structure/behavior of the `salt_formulas` Pillar key.  Please refer to discussion in issue #201.

Revert PR #200

---

salt/files/minion.d/f_defaults.conf

Updated the minion config f_defaults.conf, 
Reverted the removal of the comments so new users can see and use these.

update 2015.8.7 version config for the minion

---

salt/files/master.d/f_defaults.conf

Current Windows repo settings do not work for a 2015.8 master.  Checked the documentation at:
* https://docs.saltstack.com/en/latest/ref/configuration/master.html#windows-software-repo-settings
Found that a number of settings have been renamed -- those changes need to be transferred to this formula.
---
Existing settings converted using the documentation:
1. `win_repo_dir_ng` => `winrepo_dir_ng`
1. `win_gitrepos_ng` => `winrepo_remotes_ng`
1. Tested: `winrepo_dir_ng`
1. Untested: `winrepo_remotes_ng`
Found a problem in the docs that needs to be fixed:
https://docs.saltstack.com/en/latest/ref/configuration/master.html#winrepo-dir:
> ```
> winrepo_dir: /srv/salt/win/repo
> ```
https://docs.saltstack.com/en/latest/ref/configuration/master.html#winrepo-dir-ng:
> ```
> winrepo_dir: …
```

Fix Windows repo settings using values from 2015.8 documentation

---

salt/map.jinja

This adds some minimal support for Windows minions.

Add Windows support to map.jinja

---

salt/files/minion.d/f_defaults.conf

After merging #204 ``mine_functions`` was accidently removed. I say accidentaly because it's still in pillar.example. I suppose it should be taken back in order to maintain backwards compatibilty.

Take mine_functions back

---

salt/cloud.sls
salt/files/cloud.providers.d/ec2.conf
salt/files/cloud.providers.d/gce.conf
salt/map.jinja
salt/master.sls
salt/minion.sls
salt/standalone.sls

Operating systems such as FreeBSD install the salt configuration files in locations other than `/etc/salt`.  The changes in this PR replace existing references to that location with the `config_path` variable, which gets overridden in *map.jinja* as appropriate.

Prefix configuration files with the suitable O/S-specific pathname

---

salt/files/cloud.providers.d/ec2.conf
salt/files/cloud.providers.d/gce.conf
salt/files/cloud.providers.d/rsos.conf
salt/files/cloud.providers.d/saltify.conf

On 2015.8.8 I get the following warning:
```
/usr/lib/python2.7/dist-packages/salt/config.py:2346: DeprecationWarning: The term 'provider' is being deprecated in favor of 'driver'. Support for 'provider' will be removed in Salt Nitrogen. Please convert your cloud provider configuration files to use 'driver'.
```
This PR renames "provider" to "driver".

Renamed "provider" to "driver"

---

pillar.example

This second master config example was causing problems when vagrant
would use the default pillar.example
Fixes #217

Comment out second master config example

---

dev/setup-salt.sh

The old ppa was being used, which was causing Salt 0.17.5 to be installed. Yuck.

Use the latest stable salt from repo.saltstack.com

---

pillar.example
salt/cloud.sls

It may be some time before we have templates for all of the possible cloud config files - especially given the number of cloud providers available. This pull requests gives the ability to configure the content of custom cloud map/profile/provider files directly from pillar data.

Ability to create non-templated cloud maps/providers/profiles

---

pillar.example
salt/files/master.d/f_defaults.conf

This PR adds support for the `auth.ldap.*` parameters in the master `f_defaults.conf` file.

Add support for master eauth LDAP config

---

pillar.example
salt/files/master.d/engine.conf

Support engine configuration

---

salt/files/minion.d/f_defaults.conf

This avoid to have `null` value rendered as `None` string. I hit this bug in `grains`.

Render config as JSON

---

salt/files/master.d/f_defaults.conf

This avoids problems when values are strings containing colons. And it
mimicks what was already done for the salt-minion's configuration file.
Fixes #233.

JSON encode values embedded in the salt-master's configuration file

---

salt/files/minion.d/f_defaults.conf

should allow to set module configuration for minions
in pillar:
salt:minion:
module_config:
test: True
test.foo: foo
test.bar:
- baz
- quo
test.baz:

add module_config for minions

---

salt/map.jinja

repo.saltstack.com handles all currently supported Debian releases as well
as all supported Ubuntu releases so this change should be fine.
Part of #180.

Use repo.saltstack.com in salt.pkgrepo for Debian-based distributions

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

These are needed for:
https://docs.saltstack.com/en/latest/ref/tops/all/salt.tops.mongo.html
https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.mongo_future_return.html

add support for mongodb settings

---

pillar.example
salt/files/master.d/f_defaults.conf

These changes add support for the S3 file server back end as described in https://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.s3fs.html.

Add support for s3fs

---

pillar.example
salt/defaults.yaml
salt/master.sls
salt/minion.sls
salt/pkgrepo/ubuntu/init.sls

This PR adds both,
the https uri is something not all people want:
- if they dont have apt-transport-https
- salt doesnt detect theres a http repo which means this repo will get added a second time

https for the ubuntu repo and option to remove /etc/salt/minion.

---

salt/map.jinja
salt/pkgrepo/init.sls

Rasbian reports back the following grain values:
```
local:
----------
os:
Raspbian
os_family:
Debian
osarch:
armhf
osmajorrelease:
8
osrelease:
8.0
```    
Ubuntu reports back the following grain values:
```
local:
----------
os:
Ubuntu
os_family:
Debian
osarch:
amd64
osmajorrelease:
14
osrelease:
14.04
```
- For Raspbian the osarch needed to be changed from other Debain os_family distributions.
- For Ubuntu the osrelease value is needed instead of osmajorrelease as other Debian os_family distributions.
Part of #180

Fix URLs in salt.pkgrepo for Raspbian & Ubuntu

---

README.rst
pillar.example
salt/files/minion.d/f_defaults.conf

This is PR to solve #246 - allowing config options to be added to the minion pillar (for minion.d) that aren't part of the default config file.

Handle config opts not part of default config.

---

pillar.example
salt/files/master.d/f_defaults.conf

- Remove extra lines with nodegroups formatting in the master.d/f_defaults.conf jinja templating
- Add the winrepo_provider configuration to work around saltstack/salt#35993

Clean-up master.d/f_defaults.conf and add winrepo_provider

---

salt/cloud.sls
salt/defaults.yaml

The salt-cloud packages automatically pull in the pycrypto and libcloud dependencies for RedHat and Debian (at least when using the SaltStack repos), so it doesn't really make sense to install these dependencies using pip. By default we no longer use pip, but the old behaviour can be restored by setting 'salt:use_pip' to True in the pillar.
There could probably be a case made for removing the pip stuff altogether, but we will leave it in for the time being to preserve some backwards compatibility.

By default don't install cloud dependencies using pip

---

pillar.example

In preparation of the new release I would like to have the option to configure the reactor and engine config on a salt minion as well:
see: 
https://docs.saltstack.com/en/develop/ref/engines/all/salt.engines.reactor.html
config engines:
https://github.com/saltstack/salt/pull/29245
sync engines:
https://github.com/saltstack/salt/pull/32507

add engine and reactor config to salt minion configuration

---

salt/standalone.sls

This feature will enable salt-minion service if master_type is set to disable on standalone minions.
From the config file:
```
Setting master_type to 'disable' let's you have a running minion (with engines and
```

add option to start minion service if master_type is set to disable

---

salt/standalone.sls

forgot to set the minion service to enable if master_type is set to disable.

fix minion daemon to be enabled if master_type is set to disable

---

salt/files/master.d/f_defaults.conf

Fix typo in salt/files/master.d/f_defaults.conf template.

typo - top_file_merging_strategy (f_defaults.conf) template

---

salt/files/master.d/f_defaults.conf

The value of ``pillar_opts`` changed its default since 2015.2 release, so we should update it here to avoid confusion. For reference please see https://github.com/saltstack/salt/commit/64060782402ee83b25612f9ad474f7fdf63c7d67

Change default value for pillar_opts

---

salt/pkgrepo/redhat/absent.sls

I found it strange that this file exists yet does nothing.

Add state that ensures pkgrepo for RedHat is absent

---

salt/files/master.d/engine.conf
salt/files/master.d/f_defaults.conf
salt/files/minion.d/engine.conf
salt/files/minion.d/f_defaults.conf

the engines are now configured using the following pillars:
- salt.master.engines
- salt.minion.engines
instead of a global salt.engines pillar.
Note: the pillar.example provided seems to assume this behaviour.
(the pillar is salt.master.engines.slack and not salt.engines.slack)
https://github.com/saltstack-formulas/salt-formula/blob/master/pillar.example#L83

make the configuration of engines specific to master or minion

---

salt/defaults.yaml
salt/gitfs/dulwich.sls
salt/map.jinja

Adds support for SmartOS zones for master, minion and gitfs. Tested against SmartOS 20161110T013148Z

Add SmartOS salt-master, minion and gitfs support

---

salt/map.jinja

Previous PR didn't set the salt config path. This fixes that.
gitfs_provider isn't being set to dulwich as per the defaults, not sure if it should - will investigate further and to another PR for that.

Correct SmartOS config path

---

salt/api.sls

The salt-api service is configured using the master config files but is not restarted when the master is restarted. We need the salt-api service to watch the master config files to ensure that any config changes are picked up.

Have salt-api service watch the master config files

---

salt/gitfs/pygit2.sls

On Ubuntu Trusty/Xenial LXD images pkg-config is not installed and its no dependency on all of "build-essential" so it does not get installed.
This PR adds **pkg-config** as dependency so libgit2 works with ssh:// and https:// git urls.

Fix pygit2-libgit2 builds on Debian like platforms.

---

pillar.example
salt/files/minion.d/beacons.conf
salt/files/minion.d/f_defaults.conf

As requested in: https://github.com/saltstack-formulas/salt-formula/issues/264

Added beacon configuration support

---

salt/map.jinja

Changes default behaviour of install `pygit2` and `libgit2` via `pacman` instead of from source on Arch Linux.
Fixes #284

Arch Linux: install pygit2 or libgit2 via pacman instead of source

---

salt/files/master.d/engine.conf
salt/files/minion.d/engine.conf

This fixes the warning with the merging of https://github.com/saltstack/salt/pull/38579

fix default dict warning with saltstack dev version

---

salt/cloud.sls
salt/gitfs/keys.sls

Some Unix variants name GID 0 "wheel".  Unfortunately, one cannot specify this group by ID, because Python conflates integer 0 with boolean False, nor can one specify this group using the string '0', because of assumptions in the Salt or Python codebases regarding group names.

 Use a different group name for GID 0 depending on the minion's O/S

---

salt/files/minion.d/f_defaults.conf

Some vars were missing {{ }}
Indentation was broken
isinstance is not available in Salt

Fixes jinja in include block

---

salt/files/master.d/f_defaults.conf

The lxc keyword are not into the reserved keyword list of master configuration file, therefore the lxc configuration get copied also into the f_default file.

fixed key reserved for lxc_profile file

---

salt/files/master.d/f_defaults.conf
salt/files/master.d/lxc_profiles.conf
salt/files/minion.d/f_defaults.conf
salt/map.jinja

!!   Not tested with an actual   !!
!!  configured `ext_pillar` yet  !!
- jinja on RHEL/CentOS 6 has no 'mapping'
test (see salt-formula issue #193)
- {% do ... %} allows no assignment, only
function calls
- of course, `type(foo) is dict` doesn't
work because it's no jinja test
- maybe `.isinstance()` would be nicer/more
reliable

Hack to make rendering work on CentOS 6

---

salt/files/master.d/f_defaults.conf

With this formula it was not possible to add external_auth settings because the pillar was not parsed properly. This is what's changed with this PR.

add salt master config template external_auth settings

---

salt/files/master.d/f_defaults.conf

To avoid log flooding with deprecation messages I moved to publisher_acl in salt master config. This PR makes the formula deal with it while it still works with client_acl option.

Add new publisher_acl to salt master config

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

* Added some missing parameters in both `{master,minion}/f_defaults.conf` files
* Kept some backward compatible values (like `hash_type: md5` instead of `sha256`) as changing them to new defaults is too disruptive (require cleaning caches, etc.)

Updated minion and master config files to 2016.11

---

salt/files/master.d/f_defaults.conf

Currently the code stumbles over these definitions:
per user, per minion
```
external_auth:
pam:
thatch:
- 'web*':
- test.*
- network.*
```
function argument limiting
```
external_auth:
pam:
my_user:
- '*':
- 'my_mod.*':
args:
- 'a.*'
- 'b.*'
kwargs:
'kwa': 'kwa.*'
'kwb': 'kwb'
```

Fix rendering of external_auth config.

---

pillar.example
salt/map.jinja
salt/pkgrepo/redhat/init.sls

SaltStack provides "versioned" repositories, this commit add a way
to set which release of salt to use.
It adds a pillar "salt:release" which can be set to a specific release
(ex: 2016.11). This release is then used to configure properly the
repositories URLs for Debian/Ubuntu/RedHat.
The default behavior is to point to 'latest', retaining the previous
behavior if the "salt:release" pillar is not set.
Related to https://github.com/saltstack-formulas/salt-formula/issues/293

add a way to set which release of saltstack to use

---

pillar.example
salt/files/master.d/f_defaults.conf
salt/files/master.d/reactor.conf
salt/files/minion.d/f_defaults.conf
salt/files/minion.d/reactor.conf

Changed variable name to `reactors`, to be similar to other variables (beacons, engines, etc) and excluded them from the `f_defaults.conf` file

Allow to specify reactors separatedly for master and minions

---

salt/files/cloud.maps.d/_saltify.conf
salt/files/cloud.profiles.d/_saltify.conf
salt/files/cloud.providers.d/_saltify.conf

I use Salt environments to provide each of my team mates the ability to develop
and test their Salt changes. And I've found that when we run this formula from
our environments against our salt-master, comments in some files change. For us
this represents an unwanted and unplanned change. I understand the intention -
to identify whow or why the file changed, but I firmly believe that we should
be able to run highstsate with test=True and only see intended changes. Here's
an example:
ID: salt-cloud-providers
Function: file.recurse
Name: /etc/salt/cloud.providers.d
Result: None
Comment: #### /etc/salt/cloud.providers.d/saltify.conf ####
The file /etc/salt/cloud.providers.d/saltify.conf is set to be changed
Started: 20:01:28.586441
Duration: 75.185 ms
Changes:
---------- …

Remove "source" comments from Saltify configs

---

salt/map.jinja

This was to resolve the following error when using this state on `2017.7.0` (with the [change to osmajorrelease](https://docs.saltstack.com/en/develop/topics/releases/nitrogen.html#grains-changes):
```
local:
Data failed to compile:
----------
Rendering SLS 'base:salt.master' failed: Jinja error: coercing to Unicode: need string or buffer, int found
/var/cache/salt/minion/files/base/salt/map.jinja(44):
---
[...]
Setup variable using grains['os_family'] based logic, only add key:values here
that differ from whats in defaults.yaml
##}
{% set osrelease = salt['grains.get']('osrelease') %}
{% set salt_release = salt['pillar.get']('salt:release', 'latest') %}
{% set os_family_map = salt['grains.filter_by']({    <======================
'Debian':  {
'pkgrepo': 'deb …
```

Fix map.jinja to work with 2017.7.0

---

pillar.example
salt/files/minion.d/f_defaults.conf

Tested on CentOS 7
An example:
```
minion:
schedule:
- highstate:
- function: state.apply
- minutes: 60
- returner: redis
```
Would result to:
```
schedule:
highstate:
function: state.apply
minutes: 60
returner: redis
```

Enable option to set minion scheduler

---

salt/defaults.yaml
salt/minion.sls

This PR addresses issue #136 and adds possibility to restart salt minion via at. This is fully optional and disabled by default to preserve backwards  compatibility.

Add restart minion via at (fixes #136)

---

pillar.example

Fixes 'TypeError: coercing to Unicode: need string or buffer, float found'

Corrected salt:release in pillar.example

---

salt/minion.sls

I have run into an issue similar to those described in #136 .  I was hoping to find a different solution then the one recently merged, mostly to not have another package dependency.
I found such a solution here, using the "bg" option in cmd.run:
https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade
This has been working on all my Linux minions better then the salt-minion restart method used in the current formula.  It should also work on Windows though I am not able to test that.
This PR changes the current default salt-minion restart behavior to that described in the linked FAQ.  It should be backward compatible and add similar functionality to salt versions without the "bg" option.
Thoughts?  Good idea?  Bad idea?

adding salt-minion restart option from official FAQ page

---

salt/files/master.d/f_defaults.conf

When you add a custom master top to the saltmaster configuration the master.sls state will fail if the config looks like:
```
master_tops:
customtop: True
```
This happens because it wil not treat the situation when you have a boolean as a value for the customtop.
See also:
https://docs.saltstack.com/en/latest/topics/master_tops/index.html
My change consists in checking for all possible values and apply the state accordingly.

Fix master_tops configuration rendering

---

salt/map.jinja

Formulas iterating over dictionaries should use the items() method instead of iteritems() because the latter method has been removed from Python 3. While the items() method in Python 2 uses more memory than iteritems(), these dictionaries are typically small (e.g., sets of settings from Pillar).

fix #296 deprecated iteritems() and replace it with items()

---

pillar.example
salt/map.jinja
salt/minion.sls

This PR adds support for installing `pynotify` when `inotify` beacons are configured on the minion. `pyinotify` is a required dependency for the `inotify` beacons to work.
The `pyinotify` package name is configurable with the `salt:lookup:pyinotify` pillar value. It will only install the package if the package name is configured and if inotify beacons are used. The default package name is configured for Debian based systems only.

Added support for installing pyinotify when using inotify beacons

---

salt/files/minion.d/f_defaults.conf

This is a proposed change that we (UW IHME) have been using in production for a few weeks, and a needed deviation from the master branch of the salt-formula
This is reasonably simple, by detecting minion pillar data with elasticsearch configuration for the returner, and spits out the necessary YAML.
Example pillar:
```
elasticsearch:
----------
functions_blacklist:
- test.ping
- saltutil.findjob
- pillar.items
- grains.items
hosts:
- 10.0.0.1:9200
- 10.0.0.2:9200
- 10.0.0.3:9200
- 10.0.0.4:9200
- 10.0.0.5:9200
index_date:
True
number_of_replicas:
1
number_of_shards:
5
states_count:
True
states_order_output:
True
states_single_index:
True
```
Example output: 
```
##########################################
elasticsearch.number_of_replicas: 1
elasticsearch.states_order_output: True …
```

Update f_defaults.conf to support elasticsearch returner

---

salt/minion.sls

Changing cmd.wait to cmd.run as recomended on the documentation: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.wait

Change cmd.wait to cmd.run

---

salt/map.jinja

they get overwritten from defaults.yaml if not specified

add also default git values for SUSE osfamily

---

pillar.example

Changed formatting in the example for a pillar to avoid warning about wrong dictionary/list format from Salt. Added a comment about the type of token.

Changed pillar example formatting for Slack

---

salt/minion.sls

So I took the simple option and assumed that ```salt-call.bat``` would be in the system path.
Fixes #337.

Fix Windows minion restart command

---

salt/map.jinja

On SmartOS the salt-api daemon is started by the salt:api service.

Set correct api_service for SmartOS

---

pillar.example
salt/api.sls
salt/cloud.sls
salt/master.sls
salt/minion.sls
salt/ssh.sls
salt/standalone.sls
salt/syndic.sls

* allow installation of specific packages versions

Add configuration for packages version

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

- I've added quotation in file_ignore_glob. Lack of quotation was causing pase error. 
- some cleanup in template, to make compiled file looks nicer.

Quotation and ipv6

---

README.rst
pillar.example
salt/map.jinja
salt/minion.sls

Add's MacOS support to minion; allowing upgrade of salt-minion's running on MacOS systems.
Tested on MacOS 10.13.3 in conjunction with Windows and Linux minions in order to test for non-MacOS minion state breakage. Windows/Linux/etc minion upgrades/config still behave as expected.
NOTE: A default value for salt_minion_pkg_source has been removed from map.jinja as 'salt_release' is no longer usable (due to repo.saltstack.com changes) as a way to generate a valid URL to download a .pkg file from. 
There are no sym/hard links on repo.saltstack.com permitting the use of 'latest' at present either. The decision to upgrade the minion by salt.minion state relies on explicit configuration defining .pkg source and version to utilise.
Users will to define salt.version, salt.salt_minion_pkg_source …

Add MacOS support; fix Issue #352

---

pillar.example
salt/files/minion.d/f_defaults.conf

The minion's returner isn't able to read the dot notation, the documentation is less-than-complete
Added whitespace and a parent key 'elasticsearch' to remediate, updated example.pillar

[Minion] [returner] [Elasticsearch] Yaml read patch + example.pillar update

---

salt/files/minion.d/f_defaults.conf

The `master_alive_interval` is getting set twice in `/etc/salt/minion.d/f_defaults.conf` which is causing the issue reported in #367. This favors the first occurrence in the template.
closes #367

only set master_alive_interval once

---

pillar.example
salt/defaults.yaml
salt/formulas.jinja
salt/formulas.sls
salt/map.jinja

Quoting from `pillar.example`:
``` yaml
salt_formulas:
git_opts:
default:
...
```
This appears to work well in general except for the `Options passed directly to the git.latest state`.  Consider the example below:
``` yaml
default:
...
options:
branch: master
remote: origin
rev: master
user: myii
dev:
...
options:
branch: dev
rev: dev
```
Compare the results before and after this commit for the `dev` env:
``` yaml
Old: {'rev': 'dev', 'branch': 'dev'}
New: {'remote': 'origin', 'rev': 'dev', 'user': 'myii', 'branch': 'dev'}
```
Now the `default` options propagate as expected.
The previous commit now allows this more appropriate resolution for #238.
I was going to put this in a separate PR but since it's closely related, I've put it here anyway -- can always put in an another PR if required. …

Improve limitations related to `git.latest` in `salt.formulas`

---

pillar.example

* Also minor unrelated updates/fixes

Update `pillar.example` for single-dir, multi-branch `salt_formulas` #239

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

This PR aims to fix #371 - i.e that pillar parameters can also have their own 'child' parameters - e.g.:
```
ext_pillar:
- git:
- master http://example.com/foo.git:
- mountpoint: /foo
- env: custom
```
It's basically a copy of how the `gitfs_remotes` section in the templates does it.

Handle pillar params with child params.

---

salt/files/minion.d/f_defaults.conf

Fixes #374 to provide support for `use_superseded` and similar config opts in minions.
I haven't seen examples of lists in master extra config, or of nested dicts rather than lists - but it wouldn't be too difficult to extend this if there's a need.

Handle extra config where value is a list (minion)

---

salt/files/master.d/f_defaults.conf

Hello,
Here is an attempt to fix the issue reported in #376.
The code is a bit similar to the one used in the _external_auth_ section, and allows to support both types of entries thanks to the [jinja](http://jinja.pocoo.org/docs/2.10/) [mapping](http://jinja.pocoo.org/docs/2.10/templates/#mapping) test.
Feel free to comment.

Support publisher_acl minion-level commands

---

salt/formulas.sls

Salt prints noisy `[ERROR   ]` messages to **stdout** when `test -e <dir>` prints to **STDERR**.  
```
[ERROR   ] Command 'test -e /srv/formulas/openssh-formula' failed with return code: 1
[ERROR   ] retcode: 1
[ERROR   ] Command 'test -e /srv/formulas/packages-formula' failed with return code: 1
[ERROR   ] retcode: 1
[ERROR   ] Command 'test -e /srv/formulas/firewalld-formula' failed with return code: 1
[ERROR   ] retcode: 1
[ERROR   ] Command 'test -e /srv/formulas/etcd-formula' failed with return code: 1
[ERROR   ] retcode: 1
``` 
This PR redirects the output to /dev/null to get rid of the noise.

Stop noise from 'test -e' check'

---

salt/defaults.yaml

This PR moves some (good) defaults from pillar.example into default.yaml.  That's what defaults.yaml is for so makes sense to me.
This PR also replaces #389 setting `output_loglevel: quiet` to shutoff unless/onlyif noise.

Move some defaults from pillar.example to defaults

---

salt/files/minion.d/f_defaults.conf

Extra config stored as a dict is iterable, but needs a different yaml structure from a list.
Since the existing code only handles the first level of the configuration and does not traverse recursively, I don't think there's much value in adding special handling for mappings.
So just treat those the same as strings (which results in a JSON string being put in the config).

Fix support for extra config values as mappings

---

salt/formulas.sls

@javierbertoli PR #390 did work. I'm still getting DEBUG output from `unless` when tests are false. 
Could this be merged as workaround.

shutoff debug output from unless

---

salt/map.jinja

Without specifying this the `salt.gitfs.gitpython` state is unusable on Arch, because it tries to install a `python-git` package which doesn't exist.

Add missing GitPython-package for Arch

---

salt/map.jinja

* All minor releases appear in an `archive` sub-directory.
* Resolves main bug in GitHub issue #364.
* Simplification of original GitHub PR #365 by @ralucasg.
---
When looking into issue #364, I ended up embarking on an [epic discussion](https://github.com/saltstack-formulas/salt-formula/issues/364#issuecomment-457110950) uncovering further issues with the current implementation of linking to https://repo.saltstack.com.  The quote below has been trimmed from that discourse, so is a little disjointed, such as the numbering in the tables.  I'm including it because it shows all of the URLs that require `archive/` before the minor release version number:
> #### Debian
> 
> #|Pin|Py|Key|Repo|Direct
> -----|-----|-----|-----|-----|-----
> …

Fix `repo.saltstack.com` URLs for pinned minor release (#364)

---

salt/osfamilymap.yaml

For osfamilymap to be useful for Debian derivatives that don't have their own apt repos,
osfamilymap should make use of the `os_family` grain rather than the `os` grain.
e.g. TurnKey Linux has the following os grains:
```
os:      
TurnKey                       
os_family:      
Debian
osarch:
amd64
oscodename:
stretch  
osfinger:
TurnKey-9
osfullname:  
TurnKey
osmajorrelease:
9      
osrelease:
9.7 
osrelease_info:
- 9      
- 7         
```
cf. vanilla Debian
```
os:         
Debian  
os_family:      
Debian
osarch:
amd64
oscodename:
stretch  
osfinger:
Debian-9
osfullname:   
Debian
osmajorrelease:
9      
osrelease:
9.6 
osrelease_info:
- 9      
- 6
```

Make pkgrepo work for Debian derivatives without their own repos

---

salt/formulas.sls

NOTE: This refactor does nothing more than modify whitespace.  No change is made to the functionality at all.
---
While looking at #403, the logic is incredibly difficult to follow.  This PR adapts the Jinja to make each much easier to comprehend and work with.
---
It's easier to appreciate the changes by viewing the [whole file](https://github.com/saltstack-formulas/salt-formula/blob/f76364c1b7afffc435656a76b8c3ed49b364579d/salt/formulas.sls) rather than the diff.
Update: After the second commit, this is the [whole file](https://github.com/saltstack-formulas/salt-formula/blob/922135df31875e928e75dc5ad18dcaba7cb3ae0f/salt/formulas.sls).

Reformat `formulas.sls` Jinja to make it easier to work with

---

salt/osfamilymap.yaml
salt/ospyvermap.yaml

* From `salt-winrepo-ng`:
- https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py2.sls
- https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py3.sls
* Close #411
---
@labmonkey42 I've prepared this blindly, since I have no available Windows minions to test on.  However, I've tested it as best I can and it produces the correct packages for both `py2` and `py3`.  Will you be able to test this out to confirm it works for both?  Until then, I will keep this PR in draft status.

fix(windows): use correct `salt-minion` package name

---

salt/osmap.yaml

According to https://repo.saltstack.com/#raspbian
Tested on Raspbian 9.

osmap: Raspbian used the Debian repo

---

.travis.yml

* Every PR is currently showing as failed and `commitlint` is never running
* Disable these two platforms in the meantime; still ten platforms being tested
* `opensuse-423` is EOL in any case
---
@javierbertoli I'm going to go ahead and merge this immediately, so that we can start benefiting from testing again on our PRs.  @noelmcloughlin has a bunch of them submitted and all showing up as failures, when they're not.

fix(travis): disable two failing platforms until they can be fixed

---

salt/defaults.yaml
salt/formulas.sls
salt/minion.sls
salt/osfamilymap.yaml

This PR fixes various package handling errors on MacOS when homebrew is used.
This PR also is workaround for https://github.com/saltstack/salt/issues/49348
And brew should be run as non-root user.

fix(macos): fix brew packaging handling

---

docs/README.rst
salt/pkgrepo/debian/absent.sls
salt/pkgrepo/debian/clean.sls
salt/pkgrepo/debian/init.sls
salt/pkgrepo/debian/install.sls
salt/pkgrepo/redhat/absent.sls
salt/pkgrepo/redhat/clean.sls
salt/pkgrepo/redhat/init.sls
salt/pkgrepo/redhat/install.sls
salt/pkgrepo/suse/absent.sls
salt/pkgrepo/suse/clean.sls
salt/pkgrepo/suse/init.sls
salt/pkgrepo/suse/install.sls

This PR aligns `pkgrepo` state to template-formula.
- rename `pkgrepo.absent` to `pkgrepo.clean` (symlinked)
- rename `pkgrepo.init.sls` to `pkgrepo.install.sls` (dereferenced)
- add standard comments to each sls file
- rename state names per standard
This PR also corrects two things-
- Update README to more accurately describe what `pkgrepo` state is for.
- Update all `pkgrepo.absent` states to use **name** defined by `pkgrepo.managed`

refactor(linux): align to template-formula & fixes

---

salt/files/minion.d/f_defaults.conf

This prevents the `return` key being duplicated in the minion config by L1205

fix(minion): Add 'return' to reserved_keys in minion config

---

test/integration/v201902-py2/controls/pkgs_spec.rb
test/integration/v201902-py3/controls/pkgs_spec.rb

* https://docs.saltstack.com/en/latest/topics/releases/2019.2.1.html
---
This is needed immediately since the Travis run fails overall without it:
* https://travis-ci.org/myii/salt-formula/builds/589618332 (current)
* https://travis-ci.org/myii/salt-formula/builds/589623368 (fixed)

test(pkgs_spec): update for `2019.2.1` release

---

test/integration/v201902-py2/controls/pkgs_spec.rb
test/integration/v201902-py3/controls/pkgs_spec.rb

* https://groups.google.com/forum/#!msg/salt-announce/a2kXUwwakqQ/f4sdBQpNDAAJ
---
Tested this on all relevant instances in my fork; confirmed these version numbers are working:
* https://travis-ci.org/myii/salt-formula/builds/596761647
* https://travis-ci.org/myii/salt-formula/builds/596766042 -- last one redone

test(pkgs_spec): reset version from `2019.2.1` back to `2019.2.0`

---

pillar.example
salt/formulas.jinja
salt/formulas.sls

Proposition of a little enhancement on salt_formulas which permits to customize git.latest options on per-formula basis.
Relevant portion of pillar.example is:
```yaml
salt_formulas:
(...)
list:
base:
- salt-formula
- postfix-formula
- nginx-formula: # We can also override some options per formula
rev: 'v1.1.0'  # Pin a version
- openssh-formula:
rev: '3e01ad8' # or pin a commit id
dev:
- salt-formula
- postfix-formula
- openssh-formula
- nginx-formula:
name: 'https://github.com/another-fork-location/salt-formula.git'
rev:  'feat/feature'
```

feat(per-formula-opts): configure git.latest state per formula

---

salt/formulas.sls

A little tweak of my last PR https://github.com/saltstack-formulas/salt-formula/pull/418 to get job done in parrallel.
Improve speed!

feat(formulas): git.latest parallelization

---

salt/cloud.sls
salt/master.sls
salt/minion.sls
salt/ssh.sls
salt/standalone.sls

Before this fix, the `file.recurse`'s source resolved to this path:
```
source:
salt://salt/master/files/master.d
```
whereas the path where are located tpls is :
` salt://salt/files/master.d`
Correction just replace `slspath` by `tplroot`
Also done everywhere slspath is used ..

fix(tpl_path): salt master conf files

---

docs/README.rst
pillar.example
salt/defaults.yaml
salt/init.sls
salt/pkgrepo/init.sls
salt/standalone.sls

Resolves #410 and helps #352.  Using this metastate is optional.
In particular, this metastate avoids having developers reinvent the wheel, i.e.  https://github.com/opensds/opensds-installer/blob/c3e8b45a75b3ce1589f0d2ae680e8302ec9c4dd2/salt/srv/salt/install/salt.sls#L1

feat(formula): add metastate per community convention

---

salt/api.sls
salt/defaults.yaml
salt/master.sls
salt/minion.sls

---
No.
It allows for minion, master, and salt-api to either ignore the state of the service or instead of enabling it, to disable it.
Check the defaults file, and play with the keys 
(master|minion|api).service.(ignore,enabled).
The reason behind these flags:
- current code always enforced the service to be enabled and running. I don't think this should be really enforced upon the user; you should allow user specify otherwise
- I actually also need the formula to not do **anything** related to the services. 
Reason: installing salt-master and salt-api inside a docker image, and in there I do not have systemd running (and current code also wrongly tries to use 'upstart' in an ubuntu container...)

Allow disabling services or just ignoring them.

---

salt/formulas.sls
test/integration/v201902-py3/controls/pkgs_spec.rb

---
No.
Fixes #459 
Use `grains`, more portable anyway
```
salt_formulas:
git_opts:
default:
baseurl: https://github.com/saltstack-formulas
{%- if grains['kernel'] in ['FreeBSD', 'OpenBSD', 'NetBSD'] %}
basedir: /usr/local/etc/salt/states/namespaces/saltstack-formulas
{%- else %}
basedir: /srv/salt/namespaces/saltstack-formulas
{%- endif %}
basedir_opts:
makedirs: True
user: root
{%- if grains['kernel'] in ['FreeBSD', 'OpenBSD', 'NetBSD'] %}
group: wheel
{%- else %}
group: root
{%- endif %}
mode: 755
minion_conf:
create_from_list: True
list:
base:
{{ '- epel-formula' if grains.os_family in ('RedHat',) else '' }}
- salt-formula
```

fix(jinja): replace version_cmp with grains lookup

---

CODEOWNERS
pillar.example
salt/defaults.yaml
salt/master.sls
salt/minion.sls
salt/pin.sls

Available only on Debian family OS-es
---
No.
#314 #358
Add ability to pin version provided via pillar using apt-pinning. Benefits of version pinning:
* prevent unwanted package upgrades during system wide upgrades like `apt-get update; apt-get upgrade`
* allow package downgrade, simple version specification is not enough for downgrade because related packages won't be downgraded, i.e. if you try to downgrade from version `3000` to `2019.2.3` with `apt-get install salt-minion=2019.2.*` you will face error because apt will try to install version 3000 of `salt-common`
All changes applicable only to Debian based OS-es.
No test written but tested on my Debian Jessie - Buster machines successfully performed upgrade from v. 2018 to v. 2019, v. 3000 and downgrade from v. 3000  to v. 2019. …

feat(package): use apt-pinning to pin specific package version

---

.github/workflows/kitchen.yml
Gemfile
Gemfile.lock
docs/README.rst
kitchen.github.yml
kitchen.vagrant.yml
salt/osfamilymap.yaml
test/integration/v3000-py3/controls/pkgs_spec.rb
test/integration/v3000-py3/controls/service_spec.rb
test/integration/v3000-py3/inspec.yml

---
No.
Add local testing for Windows using Vagrant.
Add CI testing for Windows using GitHub Actions.
Fix a regression in Windows default values.

Add testing for Windows (both local and CI)

---

salt/master.sls
salt/minion.sls

When running a high-state on the salt-master to deploy itself, the run fails
with an Authentication error occurred because the master restarts half way though.
---
No.

fix(service): service salt-master and salt-minion to restart last

---

.travis.yml
kitchen.yml
test/integration/v201902-py2/inspec.yml
test/integration/v201902-py3/inspec.yml
test/integration/v3000-py2/inspec.yml
test/integration/v3000-py3/inspec.yml
test/integration/v3001-py3/inspec.yml
test/salt/pillar/salt.sls

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/269

feat: add Gentoo support

---

.gitlab-ci.yml
.travis.yml
kitchen.yml
salt/osfamilymap.yaml
salt/pkgrepo/suse/install.sls
test/integration/share/README.md
test/integration/share/libraries/system.rb
test/integration/v3000-py3/files/_mapdata/opensuse-15.yaml
test/integration/v3001-py3/files/_mapdata/opensuse-15.yaml
test/integration/v3001-py3/files/_mapdata/opensuse-tumbleweed.yaml
test/integration/v3002-py3/files/_mapdata/opensuse-15.yaml
test/integration/v3002-py3/files/_mapdata/opensuse-tumbleweed.yaml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/288
Also fix openSUSE Leap-15.2 and introduce openSUSE Tumbleweed.

ci(kitchen+gitlab): update for new pre-salted images

---

pillar.example
salt/osfamilymap.yaml
salt/osmap.yaml
salt/pkgrepo/debian/install.sls
test/integration/v3001-py3/files/_mapdata/debian-10.yaml
test/integration/v3001-py3/files/_mapdata/debian-9.yaml
test/integration/v3002-py3/files/_mapdata/debian-10.yaml
test/integration/v3002-py3/files/_mapdata/debian-9.yaml

---
- [x ] `[fix]`      A bug fix
Considering that signed-by was already the default, limiting the default repo config to Stretch and newer, there should be none. 
See commit message. Update to modern defaults for Debian and Raspbian. Fix issue with custom repos in Bullseye.
salt:py_ver: py3 can be removed on most Debian installs.
Repo management succeeds by default on Rasbian and Debian Bullseye.

Fix repo management on Debian Bullseye and newer.

---

salt/files/master.d/f_defaults.conf
test/integration/default/files/_mapdata/almalinux-8.yaml
test/integration/default/files/_mapdata/amazonlinux-2.yaml
test/integration/default/files/_mapdata/arch-base-latest.yaml
test/integration/default/files/_mapdata/centos-7.yaml
test/integration/default/files/_mapdata/centos-8.yaml
test/integration/default/files/_mapdata/debian-10.yaml
test/integration/default/files/_mapdata/debian-11.yaml
test/integration/default/files/_mapdata/debian-9.yaml
test/integration/default/files/_mapdata/fedora-33.yaml
test/integration/default/files/_mapdata/fedora-34.yaml
test/integration/default/files/_mapdata/freebsd-12.yaml
test/integration/default/files/_mapdata/freebsd-13.yaml
test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
test/integration/default/files/_mapdata/openbsd-6.yaml
test/integration/default/files/_mapdata/openbsd-7.yaml
test/integration/default/files/_mapdata/opensuse-15.yaml
test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml
test/integration/default/files/_mapdata/oraclelinux-7.yaml
test/integration/default/files/_mapdata/oraclelinux-8.yaml
test/integration/default/files/_mapdata/rockylinux-8.yaml
test/integration/default/files/_mapdata/ubuntu-18.yaml
test/integration/default/files/_mapdata/ubuntu-20.yaml
test/integration/default/files/_mapdata/windows-10.yaml
test/integration/default/files/_mapdata/windows-2016-server.yaml
test/integration/default/files/_mapdata/windows-2019-server.yaml
test/integration/default/files/_mapdata/windows-8.yaml
test/salt/pillar/salt.sls

---
No.
https://github.com/saltstack-formulas/salt-formula/issues/383
This allows for the default external pillar configuration for saltclass to be used.  Nested lists did not accept string values previously on child ext_pillar configs.
The change to the pillar top in the test should cover this

Fix: master.d template to support saltclass ext_pillar config

---

salt/files/minion.d/f_defaults.conf

---
No.
`environment` is being deprecated, renamed to `saltenv`. I added the latter in the minion's config, without removing the former, as it's still supported.

fix(minion): update config parameter saltenv

---

salt/minion.sls

---
No.
salt-cloud creates the initial minion config and certificates with the permissions of the user it's connected as.
These checks make sure the permissions are the same as in a non salt-cloud setup.

Ensure correct permissions for salt-cloud generated files

---

docs/README.rst
pillar.example
salt/osfamilymap.yaml
salt/osfingermap.yaml
salt/osmap.yaml
salt/pkgrepo/debian/absent.sls
salt/pkgrepo/debian/clean.sls
salt/pkgrepo/debian/install.sls
salt/pkgrepo/redhat/install.sls

---
No. The Formula was broken since the migration after all.
Resolves: https://github.com/saltstack-formulas/salt-formula/issues/565
Obsoletes: https://github.com/saltstack-formulas/salt-formula/pull/561
Maybe can closes: https://github.com/saltstack-formulas/salt-formula/issues/545
Update logic following the migration to `packages.broadcom.com`. For further info, see:
-> https://saltproject.io/blog/upcoming-salt-project-docs-and-repo-migration/
-> https://docs.saltproject.io/salt/install-guide/en/latest/

feat(pkgrepo): impl new logic after migration to `packages.broadcom.com`
