salt/cloud.sls
salt/master.sls
salt/minion.sls
salt/ssh.sls
salt/standalone.sls
salt/syndic.sls

Update sls files to match name change in map.jinja.

Fix: pkgs is undefined

---

pillar.example
salt/files/master.d/_defaults.conf

Add 'mine_functions' into master's configuration template

Add mine_functions to master config template

---

pillar.example
salt/files/master.d/_defaults.conf

Reverts saltstack-formulas/salt-formula#91

Revert "Add mine_functions to master config template"

---

salt/map.jinja

small fix for opensuse /suse os family

fix suse os_family

---

README.rst
salt/defaults.yaml
salt/gitfs/dulwich.sls
salt/gitfs/gitpython.sls
salt/gitfs/pygit2.sls

Add modules for gitfs dependencies and documentation for how to use them.

Add modules to install gitfs backend dependencies

---

salt/formulas.sls

This PR fixes #131 
just use an empty dic to iteritem over.

fix empty formulas list in pillar with empty dic.

---

salt/syndic.sls

I introduced a syntax error in my previous pull request. This fixes it.

Fix syntax error

---

salt/files/master.d/f_defaults.conf

Added config setting for:
* pillar_source_merging_strategy

Updated master.d/f_defaults for 2014.7

---

README.rst
pillar.example
salt/api.sls
salt/defaults.yaml
salt/gitfs/gitpython.sls
salt/map.jinja

Revert a bunch of bad commits that shouldn't have been committed in the first place.

Revert bad

---

salt/api.sls

Also watch salt-api pkg instead of salt-master one.

Only watch salt-api package if install_packages=true

---

salt/formulas.sls

Replace deprecated iteritems() with items()

---

README.rst
salt/pkgrepo/redhat/init.sls

Replace pkgrepo with offical Saltstack repo

---

salt/files/master.d/f_defaults.conf

Updated to f_defaults.conf file to latest salt version 2015.8.7

merge options from 2015.8.7 version in f_defaults.conf

---

FORMULA

Added FORMULA file for salt spm

add formula file this fixes #211

---

salt/files/cloud.providers.d/ec2.conf
salt/files/cloud.providers.d/gce.conf
salt/files/cloud.providers.d/rsos.conf
salt/files/cloud.providers.d/saltify.conf

#215 breaks versions lower than 2015.8, this should fix it.

Added version check for provider/driver backwards compatibility

---

pillar.example
salt/files/master.d/lxc_profiles.conf

Enable lxc.profiles configuration as described in https://docs.saltstack.com/en/latest/topics/tutorials/lxc.html#tutorial-lxc-profiles

Lxcprofile

---

salt/files/master.d/f_defaults.conf

https://docs.saltstack.com/en/latest/ref/configuration/master.html#yaml-utf8

Add yaml_utf8 option to salt master configuration.

---

salt/files/minion.d/engine.conf
salt/files/minion.d/reactor.conf

add missing files for reactor en engins config.

add missing files

---

salt/files/master.d/f_defaults.conf

Documented in https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-id
Fixes #262

Adding support for master_id option 

---

salt/map.jinja

Adds basic Alpine Linux support
Fixes #286

Alpine Linux: add basic support

---

salt/files/minion.d/beacons.conf

same thing as in pull request https://github.com/saltstack-formulas/salt-formula/pull/279
fix default dict warning with saltstack dev version

fix beacons on dev

---

salt/files/master.d/f_defaults.conf

Fix oops [@aboe76 found](https://github.com/saltstack-formulas/salt-formula/pull/304#pullrequestreview-31854271) in PR #304

Wrong list name in config file

---

salt/map.jinja

As discussed in #331, add pyinotify entry for Gentoo.

Add pyinotify entry for Gentoo, refs #331

---

salt/files/master.d/f_defaults.conf

fix space around peer run
Convert extra configs from json to yaml

peer run space and jason to yaml

---

pillar.example
salt/map.jinja
salt/minion.sls

Refer to issue #350 already raised

pillar.example is incorrect; package name for windows is incorrect #350

---

salt/files/master.d/f_defaults.conf

python3 iteritems is deprecated.

fix iteritems python3

---

salt/files/minion.d/f_defaults.conf

Handle other non-iterable values like int/float.

---

.kitchen.yml
.travis.yml
Gemfile
README.rst
test/integration/default/pkgs_spec.rb
test/integration/default/service_spec.rb

add initial travis integration

---

salt/formulas.sls

This reverts commit 2a0f4617db51ab74e2f3c41f5c5ec53074632836.
* Close #403

Fix regression #403

---

.travis.yml
kitchen.yml
test/integration/v201902-py2/controls/pkgs_spec.rb
test/integration/v201902-py3/controls/pkgs_spec.rb

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/86
* Similar to #438, required now since tests are failing since `2019.2.2` has been released
* https://docs.saltstack.com/en/latest/topics/releases/2019.2.2.html
This PR needs to be merged immediately since the Travis run fails overall without it.

ci(kitchen+travis): upgrade matrix after `2019.2.2` release

---

dev/setup-salt.sh

---
No.
This fixes a small error that shellcheck found.

fix(shellcheck): fix shellcheck error

---

test/integration/v201902-py3/controls/pkgs_spec.rb

---
No.
* https://travis-ci.com/saltstack-formulas/salt-formula/jobs/261961203#L1619-L1632
This needs to be merged ASAP because the tests are failing on `opensuse`.

test(pkgs_spec): update for new `opensuse` package

---

.gitignore
Vagrantfile
dev/setup-salt.sh

* add Vagrant temp files to .gitignore
* Update Vagrant Basebox to bento/ubuntu-18.04 (bento images deliver better Vagrant integration)
* Update Vagrant setup-salt.sh to use the current salt bootstrap script.
#347 
---
No.

refactor(vagrant): switch image

---

salt/pkgrepo/nop/clean.sls
salt/pkgrepo/nop/init.sls
salt/pkgrepo/nop/install.sls

chore(cleanup): delete  unused directory

---

test/integration/v201803-py2/controls/pkgs_spec.rb
test/integration/v201902-py2/controls/pkgs_spec.rb
test/integration/v201902-py3/controls/pkgs_spec.rb

---
No.
Bump salt package versions for Travis

test(versions): bump salt pkg versions for travis

---

.travis.yml
kitchen.yml
test/integration/v201803-py2/controls/service_spec.rb
test/integration/v201902-py2/controls/service_spec.rb
test/integration/v201902-py3/controls/service_spec.rb
test/integration/v3000-py3/controls/pkgs_spec.rb
test/integration/v3000-py3/controls/service_spec.rb

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/146

ci(kitchen+travis): adjust matrix to update `3000` to `3000.1`

---

salt/api.sls

---
No.
Spurious colon causes
```
Rendering SLS 'base:salt.api' failed: mapping values are not allowed in this context
```

Remove spurious colon in salt.api state

---

.travis.yml
kitchen.yml
salt/osfamilymap.yaml
test/integration/v201902-py3/controls/pkgs_spec.rb
test/integration/v3000-py3/controls/pkgs_spec.rb

---
No.
CI changes:
* Automated using https://github.com/myii/ssf-formula/pull/195

ci(kitchen+travis): adjust matrix to add `opensuse-leap-15.2`

---

test/integration/v201902-py2/controls/pkgs_spec.rb
test/integration/v201902-py3/controls/pkgs_spec.rb
test/integration/v3000-py2/controls/pkgs_spec.rb
test/integration/v3000-py3/controls/pkgs_spec.rb

* https://travis-ci.org/github/myii/salt-formula/jobs/692337807#L2366-L2381
- `opensuse` now has `3000.3` available
* Simplification is useful anyway, even without this (could still use `case`)
---
No.

test(pkgs_spec): simplify using `match` (trigger: update for `suse`)

---

.travis.yml
FORMULA
kitchen.yml
test/integration/v201902-py3/inspec.yml
test/integration/v3000-py2/inspec.yml
test/integration/v3000-py3/inspec.yml
test/integration/v3001-py3/README.md
test/integration/v3001-py3/controls/pkgs_spec.rb
test/integration/v3001-py3/controls/service_spec.rb
test/integration/v3001-py3/inspec.yml
test/salt/pillar/v3001-py3.sls

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/230
Tested across all instances:
* https://travis-ci.org/github/myii/salt-formula/builds/701176687
* https://travis-ci.org/github/myii/salt-formula/builds/701189870

ci(kitchen+travis): adjust matrix to add `3001`

---

salt/minion.sls

---
No.
Don't try to install `at` command as it is already present in Base System

fix(freebsd): command `at` is already present in base system

---

salt/master.sls
salt/minion.sls

fix(minion): fix requisites from recent prs

---

salt/defaults.yaml
salt/formulas.sls
salt/init.sls
salt/master.sls
salt/osfamilymap.yaml
salt/osmap.yaml

---
No.
Related to one failed state in #485 
Fix #485 
This PR prevents running the master state on Windows

fix(windows): various fixes

---

salt/files/cloud.providers.d/_ec2.conf

---
No.
Set the `metadata-server-grains` minion option to `True` in the default EC2 provider.
See: https://docs.saltstack.com/en/latest/ref/grains/all/salt.grains.metadata.html
See: https://docs.saltstack.com/en/latest/ref/grains/all/salt.grains.metadata.html

feat: enable the metadata grains server by default

---

.gitlab-ci.yml
.travis.yml
kitchen.yml
test/integration/v3002-py3/README.md
test/integration/v3002-py3/controls/pkgs_spec.rb
test/integration/v3002-py3/controls/service_spec.rb
test/integration/v3002-py3/inspec.yml
test/salt/pillar/v3002-py3.sls

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/280
Tested across all instances:
* https://gitlab.com/myii/salt-formula/-/pipelines/232536333

ci(kitchen+gitlab): adjust matrix to add `3002`

---

pillar.example
salt/osfamilymap.yaml
salt/osmap.yaml
test/integration/v3000-py2/files/_mapdata/ubuntu-16.yaml
test/integration/v3000-py2/files/_mapdata/ubuntu-18.yaml
test/integration/v3000-py3/files/_mapdata/debian-10.yaml
test/integration/v3000-py3/files/_mapdata/debian-9.yaml
test/integration/v3000-py3/files/_mapdata/ubuntu-16.yaml
test/integration/v3000-py3/files/_mapdata/ubuntu-18.yaml
test/integration/v3001-py3/files/_mapdata/debian-10.yaml
test/integration/v3001-py3/files/_mapdata/debian-9.yaml
test/integration/v3001-py3/files/_mapdata/ubuntu-16.yaml
test/integration/v3001-py3/files/_mapdata/ubuntu-18.yaml
test/integration/v3001-py3/files/_mapdata/ubuntu-20.yaml
test/integration/v3002-py3/files/_mapdata/debian-10.yaml
test/integration/v3002-py3/files/_mapdata/debian-9.yaml
test/integration/v3002-py3/files/_mapdata/ubuntu-16.yaml
test/integration/v3002-py3/files/_mapdata/ubuntu-18.yaml
test/integration/v3002-py3/files/_mapdata/ubuntu-20.yaml

Make the upstream salt package repository selectable, thus allowing the use of archived salt versions (hosted in http://archive.repo.saltproject.io), as well as custom salt versions hosted in alternate repositories.
---
No.

feat: allow selecting alternate salt package repositories

---

salt/api.sls
salt/master.sls
salt/standalone.sls
salt/syndic.sls

---
No.
Use the `retry_options` already being used for the Salt minion service,
since we're getting failures such as this one:
* https://github.com/myii/salt-formula/runs/2415072504
This is made worse by the fact that GitHub Actions cannot re-run a
single job (at the current time).

fix(freebsd): use `retry_options` to avoid spurious service failures

---

docs/README.rst

---
No.
This addresses #326, small doc change.
Some small documentation to make it easier for new users.
n/a
n/a
- [ x] Updated the `README` (e.g. `Available states`).

docs(readme): add documentation regarding salt.formula and salt.master, addressing #326

---

.github/workflows/kitchen.vagrant.yml
kitchen.windows.yml
salt/osmap.yaml
test/integration/v3000-py2/controls/pkgs_spec.rb
test/integration/v3000-py3/controls/pkgs_spec.rb
test/integration/v3001-py3/controls/pkgs_spec.rb
test/integration/v3002-py3/controls/pkgs_spec.rb
test/integration/v3002-py3/files/_mapdata/freebsd-11.yaml
test/integration/v3002-py3/files/_mapdata/freebsd-12.yaml
test/integration/v3002-py3/files/_mapdata/freebsd-13.yaml
test/integration/v3003-py3/controls/pkgs_spec.rb
test/integration/v3003-py3/files/_mapdata/freebsd-11.yaml
test/integration/v3003-py3/files/_mapdata/freebsd-12.yaml
test/integration/v3003-py3/files/_mapdata/freebsd-13.yaml

---
No.
* https://github.com/saltstack/salt-bootstrap/pull/1574
* Automated using https://github.com/myii/ssf-formula/pull/341 (second commit)
Available packages on FreeBSD have changed to the `py38-*` versions.
The FreeBSD CI has been disabled by this PR, until the pre-salted Vagrant boxes
can be updated once the `salt-bootstrap` PR is merged (or otherwise).

feat(freebsd): update packages from `py37-*` => `py38-*`

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

Ensure extra options in generated configuration is sorted, to ensure stable
configuration.
---
No.
Just ensure extra (not otherwised known) options are placed in a stable order.

fix: sort extra options in configuration

---

salt/files/master.d/f_defaults.conf
salt/files/minion.d/f_defaults.conf

When option was specified, it appeared twice in config, making configuration
file buggy, and not loaded.
---
No.
log_fmt_console can now be specified without breaking the generated config files.
```
salt:
master:
log_fmt_console: '%(colorlevel)s %(colormsg)s'
minion:
log_fmt_console: '%(colorlevel)s %(colormsg)s'
```

fix(log_fmt_console): double option in config

---

salt/minion.sls

fix(minion): respect `minion_remove_config: true`

---

salt/pkgrepo/suse/install.sls

---
No.
in pkgrepo/suse/install.sls there was a solution (hack) to grep for baseurl, this was failing because
of cmd.run in states can't use "pipes" see https://github.com/saltstack/salt/issues/44226
switch this to cmd.shell.

fix(pkgrepo): pkgrepo use cmd.shell

---

.github/workflows/kitchen.macos.yml
kitchen.macos.yml
salt/minion.sls
salt/osfamilymap.yaml
test/integration/default/controls/pkgs_spec.rb
test/integration/default/controls/service_spec.rb
test/integration/default/files/_mapdata/mac_os_x-10.yaml
test/integration/default/files/_mapdata/mac_os_x-11.yaml
test/integration/default/files/_mapdata/mac_os_x-12.yaml
test/integration/default/inspec.yml

---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/443
Add macOS testing using the available GitHub Actions runners (using the Kitchen `exec` driver).
Fix various issues along the way.
Already present.
As seen in the CI.

ci(macos): enable testing using GitHub Actions

---

kitchen.vagrant.yml
kitchen.windows.yml

test(windows): fix URL for winrepo`s `salt-minion.sls`

---

.pre-commit-config.yaml
.yamllint

---
No.
* only run `yamllint` when relevant files have changed
* avoids having to exclude files/dirs not tracked by Git e.g. .kitchen/, .bundle/ etc.
* avoids a `yamllint` bug whereby pillar files under `test/` were not checked due to a conflicting `ignore` entry

test(pre-commit): switch to using `pre-commit`'s built-in file filtering
